### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Mysterius** [piepieonline/ShadowsOfDoubtMods#1]
Hello,

It doesn't seem to work with newe versions.

> [Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.MissingMethodException: Method not found: '!!0 Newtonsoft.Json.JsonConvert.DeserializeObject(System.String)'.
   at AssetBundleLoader.BundleLoader.LoadBundle(String bundlePath, Boolean skipCache, Boolean stable)
   at CruncherSolitaire.CruncherSolitaireHooks.MainMenuController_Start.Prefix() in D:\Game Modding\ShadowsOfDoubt\_Mods\ShadowsOfDoubtMods\CruncherSolitaire\CruncherSolitairePlugin.cs:line 79
   at DMD<MainMenuController::Start>(MainMenuController this)
   at (il2cpp -> managed) Start(IntPtr , Il2CppMethodInfo* )

**Comment by p0pethegreat** [comment]
Having the same issue, with this and with Real Estate Cruncher App

**Comment by piepieonline** [comment]
Yea, both of these mods broke with the most recent update. I've paused updating them until we get the mono branch, which should happen in the next month hopefully.
